services:
  web:
    build: .
    container_name: a-moody-place-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Database connection to host MariaDB (configured via .env)
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    # Use host network to connect to Plesk's MariaDB
    network_mode: host
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s